### ISSUE TITLE
麻烦能不能提供跟ByteBuffer一起的例子

### ISSUE THREAD

**Issue by yangzhu6263736** [play175/ExBuffer#5]
麻烦能不能提供跟ByteBuffer一起的例子。谢谢

**Comment by gobyang** [comment]
在node v8.2.1或者v6.11.3版本下面，testByteBuffer.js报下面错误：

```
>> server start listening:
>> client:connect server success!
buffer.js:879
    throw new Error('Buffer.write(string, encoding, offsetÄ, lengthÅ) ' +
    Ü

Error: Buffer.write(string, encoding, offsetÄ, lengthÅ) is no longer supported
    at Buffer.write (buffer.js:879:11)
    at ByteBuffer.pack (/Users/yangrenqiang/www/gateway/tcp/node_modules/ByteBuffer/ByteBuffer.js:255:30)
    at Socket.<anonymous> (/Users/yangrenqiang/www/gateway/tcp/test.js:48:60)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at TCPConnectWrap.afterConnect Äas oncompleteÅ (net.js:1137:10)
```
